install.packages('tidyverse')
install.packages('moments')
install.packages("ggrepel")
install.packages('psych')
install.packages('RSQLite')
install.packages('babynames')
install.packages('nycflights13')
install.packages('esquisse')